title: ONE WITH NOW
baseurl: /
url: "http://onewithnow.github.io"
permalink: /:title/

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

exclude: ['README.md']